name: health_tracker
description: "A Health Tracker App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1

  # Backend & API
  supabase_flutter: ^2.5.0
  google_sign_in: ^7.1.1

  # Local Storage
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.2
  path_provider: ^2.1.5

  # Routing
  auto_route: ^10.1.0

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Models & Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  connectivity_plus: ^5.0.2
  gap: ^3.0.1
  overlay_support: ^2.1.0
  uuid: ^4.5.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Test
  mockito: ^5.4.6

  # Code Generators
  build_runner: ^2.4.8
  auto_route_generator: ^10.1.0
  injectable_generator: ^2.4.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300

flutter_gen:
  output: lib/core/gen_assets
